title: Gao Xingming's Homepage
page-top-title: Gao Xingming
top-section-bg-text: Be what you wanna be
home-subtitle: Gao Xingming&ensp;|&ensp; 高兴明
copyright-text: '&copy; Gao Xingming 2023-2025. All Rights Reserved.'
